# version: '3.8' #Bug with the version says obsolete version
services:
  app:
    container_name: weather-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    
