services:
- type: web
  name: assignment-01-weather-app
  runtime: docker
  repo: https://github.com/iitjvk/assignment-01-weather-app
  plan: free
  envVars:
  - key: .env
    sync: false
  - key: API_KEY
    sync: false
  - key: PORT
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
